/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if an absolute indirect call/jump must NOT be prefixed with `*' */
/* #undef ABSOLUTE_WITHOUT_ASTERISK */

/* Define it to \"addr32\" or \"addr32;\" to make GAS happy */
#define ADDR32 addr32

/* Define if you don't want to pass the mem= option to Linux */
#define AUTO_LINUX_MEM_OPT 1

/* Define it to \"data32\" or \"data32;\" to make GAS happy */
#define DATA32 data32

/* Define if C symbols get an underscore after compilation */
/* #undef HAVE_ASM_USCORE */

/* Define to 1 if you have the <curses.h> header file. */
#define HAVE_CURSES_H 1

/* Define if edata is defined */
#define HAVE_EDATA_SYMBOL 1

/* Define if end is defined */
#define HAVE_END_SYMBOL 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if you have a curses library */
#define HAVE_LIBCURSES 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ncurses/curses.h> header file. */
#define HAVE_NCURSES_CURSES_H 1

/* Define to 1 if you have the <ncurses.h> header file. */
#define HAVE_NCURSES_H 1

/* Define if opendisk() in -lutil can be used */
/* #undef HAVE_OPENDISK */

/* Define if start is defined */
/* #undef HAVE_START_SYMBOL */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if _edata is defined */
#define HAVE_USCORE_EDATA_SYMBOL 1

/* Define if end is defined */
#define HAVE_USCORE_END_SYMBOL 1

/* Define if _start is defined */
#define HAVE_USCORE_START_SYMBOL 1

/* Define if __bss_start is defined */
//#define HAVE_USCORE_USCORE_BSS_START_SYMBOL 0

// plese run check_compile_funcs.c to get the settings above.
//   DGJPP doesnot support __bss_start
//

/* Name of package */
#define PACKAGE "grub"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bug-grub@gnu.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "GRUB"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "GRUB 0.97"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "grub"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.97"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.97"

// AVLGO
#define AVLGO_NAME "Avlgo"
#define AVLGO_LONGNAME " Avlgo - Virtual Disk Loader based on " PACKAGE_STRING

// Author
#define AVLGO_AUTHOR "Gandalf"

// EMail
#define AVLGO_EMAIL "ganstein@gmail.com"

// HomePage
#define AVLGO_HOMEPAGE "http://sysoft.zdwx.com/AVLGO"

// Year
#define AVLGO_YEARS "2006"

// copyright
#define AVLGO_LICENCE "General Public Licence (GPL)"

// Compile Time
#define AVLGO_COMPILIEDTIME __DATE__ " " __TIME__

#define AVLGO_MINI_GRUB     1
/* Define if there is user specified preset menu string */
#define PRESET_MENU_STRING "#\ndefault 0\n\ntitle fff\nreboot\n\n"
